### ISSUE TITLE
Other MODX extras use jQuery too

### ISSUE THREAD

**Issue by Jako** [theboxer/markdown-editor#10]
MarkdownEditor uses a combined dependencies.js with a jQuery version inside that kills all jQuery scripts registered before. Image+ uses another jQuery version. The later included file wins. See: https://github.com/Jako/ImagePlus/issues/7#issuecomment-118561643

I really should switch to Cropper which is way better than jCrop and update jQuery to 2.x but then we have the same situation as before, because both scripts are included (they have different folder names and so they have different file names for MODX).

So it is more the fault of the MODX regClientScript system that does not allow dependencies and version checks, but how could Image+ and MarkdownEditor live beneath each other? Is there any mechanism that avoids the issue?

**Comment by theboxer** [comment]
I'll use noConflict mode, just tried and worked fine :)

**Comment by Jako** [comment]
Ok, thought about require.js

Von meinem iPhone gesendet

**Comment by jpdevries** [comment]
we have to use `noConflict` with Redactor for MODX as well and recently submitted a PR to AssetManager to do the same. 
https://github.com/craftsmancoding/assetmanager/pull/61/files

It's probably best practice for any Extra that uses jQuery to use `noConflict`.

In future MODX versions, hopefully we can propose something to work around this madness of managing sub dependencies
