### ISSUE TITLE
Drag and drop upload doesn't work

### ISSUE THREAD

**Issue by mazuhl** [theboxer/markdown-editor#14]
Just tried this on two blank MODX installs and the image uploader doesn't work out of the box. The crop box does pop up, but after cropping an error is displayed "No image".

Environment:
MODX Version 2.3.3-pl
PHP Version 5.5.28
Compress CSS/JS disabled
/assets/u folder created

**Comment by theboxer** [comment]
Hard to tell without any error message. Please look at error log if there is anything. I have no problem using the uploader on MODX 2.3.3
