### ISSUE TITLE
[Error] Can't find autoload.php after installation with GPM

### ISSUE THREAD

**Issue by hugopeek** [TheBoxer/markdown-editor#5]
```
Fatal error: require_once(): Failed opening required '/Users/Hugo/Localhost/bootqamp-pkg2/packages/markdown/core/components/markdowneditor/model/vendor/autoload.php' (include_path='.:') in /Users/Hugo/Localhost/bootqamp-pkg2/packages/markdown/core/components/markdowneditor/model/markdowneditor/markdowneditor.class.php on line 127
```
Vendor folder is not supposed to be there I think..?

**Comment by TheBoxer** [comment]
http://theboxer.github.io/markdown-editor/contributing/#installation

**Comment by hugopeek** [comment]
Ok, so you mean you also need to build the package, after installing it with GPM? I thought that was the hard way.. ;)

**Comment by TheBoxer** [comment]
no, you just need to run composer install to fetch dependencies

**Comment by hugopeek** [comment]
That did the trick, thanks.

Amazing, amazing work, also by @rthrash and anyone else that helped. This is premium stuff, am so happy with it!

**Comment by TheBoxer** [comment]
:+1:
