### ISSUE TITLE
Parse error: syntax error, unexpected T_USE

### ISSUE THREAD

**Issue by beau-gosse** [TheBoxer/markdown-editor#6]
Getting the following error when attempting to edit a resource:
> Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in edited-server-path/core/components/markdowneditor/model/markdowneditor/oEmbed/Service/Essence.php on line 10

**Here's my environment:**
* MODX 2.3.1
* Markdown Editor 1.0.0-pl
* Ace 1.5.0-pl (currently set as default code editor in system settings)
* PHP 5.3.29
* MySQL 5.1.72

**Comment by TheBoxer** [comment]
Minimal requirement is PHP 5.4 - http://theboxer.github.io/markdown-editor/#requirements

**Comment by beau-gosse** [comment]
Sorry I missed that.
