### ISSUE TITLE
WYSIWYG Markdown Editor

### ISSUE THREAD

**Issue by jenswittmann** [theboxer/markdown-editor#8]
Maybe a good alternative with WYSIWYG?
http://bevacqua.github.io/woofmark/

**Comment by TheBoxer** [comment]
Hello,

I don't really see any benefit in adding toolbar buttons to markdown editor. I think markdown syntax is pretty easy to learn and with very basic knowledge it is faster to type whole markup than selecting text, finding right icon and clicking it.

Also as the wysiwyg can be considered the live preview panel.
