### ISSUE TITLE
Markdown hides Buttons/scrolling in Collections View

### ISSUE THREAD

**Issue by jenswittmann** [theboxer/markdown-editor#9]
Hello,
ive got Collections and Markdown Editor installed. In this way, you can't scroll inside the Collections View and the save buttons are hidden.

``Uncaught TypeError: Cannot read property 'dom' of null``

Hope we can fix it. Thanks!

**Comment by theboxer** [comment]
Hey,

not sure if I follow your problem, I have collections installed as well and everything works as expected... Can you please provide more detail and attach screenshots/video?

**Comment by jenswittmann** [comment]
Hello,
thanks for your answers!

Here is an example: http://quick.as/kzrbuojdw

MODX-Version: MODX Revolution 2.3.3-pl (traditional)
PHP Version: 5.5.24

**Comment by jenswittmann** [comment]
I hide the content field with collections, if i put it in a tab it works! Seems there is a problem when the content field isnt visible?

**Comment by theboxer** [comment]
Oh, I was able to reproduce :), Yes, the problem is missing content field, For now I would suggest using `In Tab` or `Original except children` as a content place, which should resolve this issue. I'll fix MD editor soon.

**Comment by jenswittmann** [comment]
Thanks a lot, Workaround is okay for now ;)
